src/tweetme/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

from tweets.views import TweetListView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TweetListView.as_view(), name="home"),
    url(r'^tweet/', include('tweets.urls', namespace="tweet")),
    url(r'^api/tweet/', include('tweets.api.urls', namespace="tweet-api")),
    url(r'^', include('accounts.urls', namespace="profile")),
    url(r'^', include('hashtags.urls', namespace="hashtag")),
]

if settings.DEBUG:
    urlpatterns += (static(settings.STATIC_URL, document_root=settings.STATIC_ROOT))

src/tweets/api/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from .views import (
    TweetListAPIView,
    TweetCreateAPIView,
    )

urlpatterns = [
    # url(r'^$', RedirectView.as_view(url="/")),
    url(r'^$', TweetListAPIView.as_view(), name="list"),
    url(r'^create/$', TweetCreateAPIView.as_view(), name="create"),
    # url(r'^(?P<pk>\d+)/$', TweetDetailView.as_view(), name="detail"),
    # url(r'^(?P<pk>\d+)/update/$', TweetUpdateView.as_view(), name="update"),
    # url(r'^(?P<pk>\d+)/delete/$', TweetDeleteView.as_view(), name="delete"),
]

src/tweets/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

from .views import (
    TweetDetailView, 
    TweetListView,
    TweetCreateView,
    TweetUpdateView,
    TweetDeleteView,
    RetweetView
    )

urlpatterns = [
    url(r'^$', RedirectView.as_view(url="/")),
    url(r'^search/$', TweetListView.as_view(), name="list"),
    url(r'^create/$', TweetCreateView.as_view(), name="create"),
    url(r'^(?P<pk>\d+)/$', TweetDetailView.as_view(), name="detail"),
    url(r'^(?P<pk>\d+)/retweet/$', RetweetView.as_view(), name="retweet"),
    url(r'^(?P<pk>\d+)/update/$', TweetUpdateView.as_view(), name="update"),
    url(r'^(?P<pk>\d+)/delete/$', TweetDeleteView.as_view(), name="delete"),
]

src/tweets/models.py
from django.conf import settings
from django.urls import reverse
from django.db import models

from .validators import validate_content

class TweetManager(models.Manager):
    def retweet(self, user, parent_obj):
        if parent_obj.parent:
            og_parent = parent_obj.parent
        else:
            og_parent = parent_obj

        qs = self.get_queryset().filter(user=user, parent=og_parent)
        if qs.exists():
            return None

        obj = self.model(
                parent = og_parent,
                user = user,
                content = parent_obj.content
            )
        obj.save()
        return obj
    



class Tweet(models.Model):
    parent      = models.ForeignKey("self", blank=True, null=True)
    user        = models.ForeignKey(settings.AUTH_USER_MODEL)
    content     = models.CharField(max_length=140, validators=[validate_content])
    updated     = models.DateTimeField(auto_now=True)
    timespamt   = models.DateTimeField(auto_now_add=True)

    objects = TweetManager()

    class Meta:
        verbose_name = "Tweet"
        verbose_name_plural = "Tweets"
        ordering = ['-timespamt', 'content']

    def __str__(self):
        return str(self.content)

    def get_absolute_url(self):
        return reverse("tweet:detail", kwargs={"pk":self.pk})

src/tweets/forms.py
from django import forms

from .models import Tweet

class TweetModelForm(forms.ModelForm):
    content = forms.CharField(label='', widget=forms.Textarea(attrs={"placeholder":"Your message", "class":"form-control", "data-length":140}))
    class Meta:
        model = Tweet
        fields = [
            "content"
        ]

src/tweets/api/views.py
from rest_framework import generics
from rest_framework import permissions
from django.db.models import Q

from tweets.models import Tweet
from .serializers import TweetModelSerializer
from .pagination import StandardResultsPagination

class TweetListAPIView(generics.ListAPIView):
    serializer_class = TweetModelSerializer
    pagination_class = StandardResultsPagination 

    def get_queryset(self, *args, **kwargs):

        im_following = self.request.user.profile.get_following()

        qs1 = Tweet.objects.filter(user__in=im_following)
        qs2 = Tweet.objects.filter(user=self.request.user)

        qs = (qs1 | qs2).distinct().order_by('-timespamt')

        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                    Q(content__icontains=query) |
                    Q(user__username__icontains=query)
                )

        return qs


class TweetCreateAPIView(generics.CreateAPIView):
    serializer_class = TweetModelSerializer
    permission_classes = [permissions.IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

src/tweets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.db.models import Q
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import (
    DetailView, 
    ListView, 
    CreateView, 
    UpdateView,
    DeleteView
    )

from .forms import TweetModelForm
from .mixins import FormUserNeededMixin, UserOwnerMixin
from .models import Tweet
# Create your views here.

class RetweetView(View):
    def get(self, request, pk, *args, **kwargs):
        tweet = get_object_or_404(Tweet, pk=pk)
        if request.user.is_authenticated():
            new_tweet = Tweet.objects.retweet(
                    request.user,
                    tweet
                )
            return HttpResponseRedirect("/")
        return HttpResponseRedirect("/")


class TweetCreateView(FormUserNeededMixin, CreateView):
    """Class to handle tweets creation"""
    form_class = TweetModelForm
    template_name = "tweets/create_view.html"

class TweetUpdateView(LoginRequiredMixin, UserOwnerMixin, UpdateView):
    """ update tweets """
    queryset = Tweet.objects.all()
    form_class = TweetModelForm
    template_name = "tweets/update_view.html"

class TweetDetailView(DetailView):
    """Detail view for tweets"""
    template_name = "tweets/detail_view.html"
    queryset = Tweet.objects.all()

class TweetListView(ListView):
    """List view for tweetes"""
    template_name = "tweets/list_view.html"
    
    def get_queryset(self, *args, **kwargs):
        qs = Tweet.objects.all()

        query = self.request.GET.get("q", None)
        if query is not None:
            qs = qs.filter(
                    Q(content__icontains=query) |
                    Q(user__username__icontains=query)
                )

        return qs

    def get_context_data(self, **kwargs):
        context = super(TweetListView, self).get_context_data(**kwargs)
        context['create_form'] = TweetModelForm()
        context['create_url'] = reverse_lazy("tweet:create")
        return context

class TweetDeleteView(DeleteView):
    """Delete tweets"""
    model = Tweet
    success_url = reverse_lazy("tweet:list")
    template_name = "tweets/delete_confirm.html"

src/tweets/templates/tweets/create_view.html
{% extends "base.html" %}

{% block title %}
    {{ block.super }} | Create Tweet
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <h1>Create tweet</h1>
            {% include "tweets/form.html" with form=form btn_title="Tweet" %}
        </div>
    </div>
{% endblock content %}

src/tweets/templates/tweets/delete_confirm.html
{% extends "base.html" %}

{% block title %}
	{{ block.super }} | Really delete {{ object }}?
{% endblock title %}

{% block content %}
	<form action="" method="post">{% csrf_token %}
	    <p>Are you sure you want to delete "{{ object }}"?</p>
	    <input type="submit" value="Confirm" />
	</form>
{% endblock content %}

src/tweets/templates/tweets/detail_view.html
{% extends "base.html" %}

{% block title %}
    {{ block.super }} | Detail
{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-sm-3">
            <h1>{{ object.user }}</h1>
        </div>

        <div class="col-sm-9">
            <p>{{ object.content }}</p>
            <p>{{ object.timespamt|timesince }}</p>
        </div>

        

    </div>
{% endblock content %}

src/tweets/templates/tweets/form.html
{% load crispy_forms_tags %}
<form {% if form_id %}id="{{ form_id }}"{% endif %} action="{% if action_url %}{{ action_url }}{% endif %}" class="form" method="POST">
	{% csrf_token %}
	
	{{ form|crispy }}

    <input class="btn btn-default" type="submit" value="{{ btn_title }}">
    <span id="tweetCharsLeft"></span>
</form>

src/tweets/templates/tweets/list_view.html
{% extends "base.html" %}

{% block title %}
    {{ block.super }} | Tweets list
{% endblock title %}

{% block content %}


    <div class="row">

        <div class="col-sm-3">
            <h1>{{ request.user }}</h1>
        </div>

        <div class="col-sm-9"> 
            {% if not request.GET.q %}
                {% include "tweets/form.html" with form=create_form btn_title="Tweet" action_url=create_url form_id="tweet-form" %}
            {% endif %}


            {% if object_list %}
            <div id="tweet-container">
                
            </div>

            <nav aria-label="Page navigation">
                <button type="button" id="load_more" class="btn btn-success">Load More...</button>
            </nav>


            {% else %}
                
                {% if request.GET.q %}
                <p>No hay resultados</p>
                {% else %}
                <p>Paila</p>
                {% endif %}

            {% endif %}
        </div>
    </div>
{% endblock content %}

{% block script %}

    <script>

        var TweetListClass = function() {
            
            var _THIS = this,
                $_TWEET = $('#id_content'),
                $_TWEET_CHARS_LEFT = $('#tweetCharsLeft'),
                $_LOAD_MORE = $('#load_more'),
                _MAX_LENGTH_TWEET = $_TWEET.data('length'),
                _CURR_LENGTH = 0,
                _NEXT_PAGE

            this.init = function(q){
                var q = q || ''
                BindElems()
                _THIS.fetchTweets(q)

                ResetForm()
            }

            this.fetchTweets = function(q){
                var q = q || '',
                    fetchUrl = (typeof _NEXT_PAGE === 'undefined')?"/api/tweet/":_NEXT_PAGE

                $.ajax({
                    url: fetchUrl,
                    data:{
                        q:q
                    },
                    method: "get",
                    success: function(data){
                        finalHtml = CreateTweetHtml(data.results)
                        $('#tweet-container').append(finalHtml)

                        _NEXT_PAGE = data.next
                        if(_NEXT_PAGE == null)
                            $_LOAD_MORE.hide()

                    }, 
                    error: function(data){
                        console.log('error')
                        console.log(data)
                    }
                })

            }

            var BindElems = function(){
                $('#tweet-form').submit(function(e){
                    e.preventDefault()
                    if(_CURR_LENGTH >= 0){
                        SaveTweet($(this))
                    } else {
                        console.log('paila')
                    }
                })

                $_TWEET.keyup(function(e){
                    var tweetValueLen = $(e.currentTarget).val().length
                    _CURR_LENGTH = _MAX_LENGTH_TWEET - tweetValueLen
                    $_TWEET_CHARS_LEFT.text(_CURR_LENGTH)

                    if(_CURR_LENGTH > 0) {
                        $_TWEET_CHARS_LEFT.removeClass('red-text')
                        $_TWEET_CHARS_LEFT.removeClass('grey-text')
                    } else if(_CURR_LENGTH == 0){
                        $_TWEET_CHARS_LEFT.removeClass('red-text')
                        $_TWEET_CHARS_LEFT.addClass('grey-text')
                    } else if(_CURR_LENGTH < 0){
                        $_TWEET_CHARS_LEFT.addClass('red-text')
                        $_TWEET_CHARS_LEFT.removeClass('grey-text')
                    }
                })

                $_LOAD_MORE.on('click', function(e){
                    e.preventDefault()
                    _THIS.fetchTweets()
                })
            }

            var SaveTweet = function($form){
                $.ajax({
                    url: "/api/tweet/create/",
                    data: $form.serialize(),
                    method: "post",
                    success: function(data){
                        finalHtml = CreateTweetHtml(data)
                        $('#tweet-container').prepend(finalHtml)
                        ResetForm($form)
                    }, 
                    error: function(data){
                        console.log('error')
                        console.log(data)
                    }
                })
                
            }

            var CreateTweetHtml = function(data){
                var finalHtml = '';


                function renderTpl(val){

                    var tpl = 'tweet'
                    if(val.parent)
                        tpl = 'retweet'


                    switch (tpl) {
                        case 'retweet':
                            return [    '<hr>',
                                        '<div class="media">',
                                            '<div class="media-body">',
                                                '<h4 class="media-heading">Retweet via '+ val.parent.user.username + ' ' + val.parent.timesince +'</h4>',
                                                '<p>'+val.content+'</p>',
                                                '<p><a href="'+val.user.url+'">via '+val.user.username+'</a> | '+ val.timesince +' | <a href="'+val.tweet_url+'">View</a></p>',
                                            '</div>',
                                        '</div>'
                                ].join(' ')
                        case 'tweet':
                            return [    '<hr>',
                                        '<div class="media">',
                                            '<div class="media-body">',
                                                '<p>'+val.content+'</p>',
                                                '<p><a href="'+val.user.url+'">via '+val.user.username+'</a> | '+ val.timesince +' | <a href="'+val.tweet_url+'">View</a></p>',
                                                '<p><a href="'+val.retweet_url+'">Retweet</a></p>',
                                            '</div>',
                                        '</div>'
                                ].join(' ')
                            break;
                        default:
                            // statements_def
                            break;
                    }
                }

                if(isNaN(data.length)){
                    finalHtml = renderTpl(data)
                } else {
                    $.each(data, function(k, val){
                        finalHtml += renderTpl(val)
                    })
                }

                finalHtml = UpdateHashLinks(finalHtml)

                return finalHtml
            }

            var ResetForm = function($form){
                $_TWEET_CHARS_LEFT.text(_MAX_LENGTH_TWEET)
                if($form){
                    $form.find('input[type="text"], textarea').val('')
                }
            }

            var UpdateHashLinks = function(finalHtml){
                var hashRegex = /#([\w\d-]+)/g
                return finalHtml.replace(hashRegex, "<a href='/tags/$1/'>#$1</a>")
            }
        }


        $(document).ready(function(){
            var objUrl = new URL(window.location.href)
            q = (objUrl.searchParams.get("q") != null)?objUrl.searchParams.get("q"):''
            var appTweetList = new TweetListClass()
            appTweetList.init(q)
        })




    </script>

{% endblock script %}

src/tweets/templates/tweets/search_form.html
<form class="navbar-form navbar-left" action="{% url 'tweet:list' %}" method="GET">
    <div class="form-group">
        <input type="text" class="form-control" id="q" name="q" placeholder="Your search" value="{{ request.GET.q }}">
    </div>
    <button type="submit" class="btn btn-default">Search</button>
</form>

src/tweets/templates/tweets/update_view.html
{% extends "base.html" %}

{% block title %}
	{{ block.super }} | Edit {{ object }}
{% endblock title %}

{% block content %}
	{% include "tweets/form.html" with form=form btn_title="Update" %}
{% endblock content %}